org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=redstone_chemical_elements
mod_name=Redstone-chan Chemical Elements
mod_license=MIT + CC BY 4.0
mod_version=1.0.0-mc1.20.1-forge
mod_group_id=com.chinaex123.redstone_chemical_elements
mod_authors=ChinaEX123
mod_description=Added 118 chemical elements and their derivative items to the game.